services:
  backend:
    build: .
    container_name: tech4bike-backend
    ports:
      - "8000:8000"
    environment:
      - DB_PATH=/app/data/tech4bike.db
    volumes:
      - backend_data:/app/data
    restart: always

volumes:
  backend_data:
